/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Entity.*;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hoaht
 */
public class EmployeeManagmentSystemForm extends javax.swing.JFrame {

    /**
     * Creates new form Copy
     */
    public EmployeeManagmentSystemForm() {
        initComponents();
        try {
            test();
        } catch (ParseException ex) {
            Logger.getLogger(EmployeeManagmentSystemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        btn_update.setVisible(false);
        btn_cancle.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btn_group_selectGender = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        txt_eAgency = new javax.swing.JTextField();
        label_gender = new javax.swing.JLabel();
        txt_ePhone = new javax.swing.JTextField();
        label_phone = new javax.swing.JLabel();
        txt_eEmail = new javax.swing.JTextField();
        label_email = new javax.swing.JLabel();
        option_male = new javax.swing.JRadioButton();
        txt_eAddress = new javax.swing.JTextField();
        option_female = new javax.swing.JRadioButton();
        label_address = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        txt_eId = new javax.swing.JTextField();
        label_firstName = new javax.swing.JLabel();
        txt_eFirstName = new javax.swing.JTextField();
        label_lastName = new javax.swing.JLabel();
        txt_eLastName = new javax.swing.JTextField();
        txt_eSalary = new javax.swing.JTextField();
        txt_eDob = new javax.swing.JTextField();
        label_salary = new javax.swing.JLabel();
        label_dob = new javax.swing.JLabel();
        label_agency = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_cancle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_listOfEmployees = new javax.swing.JTable();
        txt_search = new javax.swing.JTextField();
        option_sortType = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_eIdSelect = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btn_wantUpdate = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label_gender.setText("Gender");

        label_phone.setText("Phone");

        label_email.setText("Email");

        btn_group_selectGender.add(option_male);
        option_male.setText("Male");
        option_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option_maleActionPerformed(evt);
            }
        });

        btn_group_selectGender.add(option_female);
        option_female.setText("Female");
        option_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option_femaleActionPerformed(evt);
            }
        });

        label_address.setText("Address");

        label_id.setText("Employee ID");
        label_id.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                label_idAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        label_firstName.setText("First name");

        label_lastName.setText("Last name");

        label_salary.setText("Salary");

        label_dob.setText("Date of birth");

        label_agency.setText("Agency");

        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_cancle.setText("CANCLE");
        btn_cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_agency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_salary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_gender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_firstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_lastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_eDob)
                            .addComponent(txt_eAddress)
                            .addComponent(txt_eEmail)
                            .addComponent(txt_ePhone)
                            .addComponent(txt_eLastName)
                            .addComponent(txt_eFirstName)
                            .addComponent(txt_eId)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(option_male, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(option_female)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_eSalary)
                            .addComponent(txt_eAgency)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_cancle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_add)))
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_eId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_eFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_eLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option_male)
                    .addComponent(option_female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_email, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_eEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_address, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_eAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_eDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_eSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_agency, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_eAgency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_clear)
                    .addComponent(btn_update)
                    .addComponent(btn_cancle))
                .addGap(5, 5, 5))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setRequestFocusEnabled(false);

        table_listOfEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First name", "Last name", "Phone", "Email", "Address", "Date of birth", "Sex", "Salary (VND)", "Agency"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_listOfEmployees.setRowHeight(30);
        table_listOfEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_listOfEmployeesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_listOfEmployees);
        if (table_listOfEmployees.getColumnModel().getColumnCount() > 0) {
            table_listOfEmployees.getColumnModel().getColumn(0).setResizable(false);
            table_listOfEmployees.getColumnModel().getColumn(0).setPreferredWidth(35);
            table_listOfEmployees.getColumnModel().getColumn(1).setPreferredWidth(50);
            table_listOfEmployees.getColumnModel().getColumn(2).setPreferredWidth(50);
            table_listOfEmployees.getColumnModel().getColumn(4).setPreferredWidth(140);
            table_listOfEmployees.getColumnModel().getColumn(5).setPreferredWidth(130);
        }

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        option_sortType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose type of sort", "Sort by salary" }));
        option_sortType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option_sortTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(option_sortType, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option_sortType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("CLICK ANY EMPLOYEE YOU WANT IN TABLE");

        jLabel12.setText("You seleted");

        txt_eIdSelect.setEditable(false);

        jButton3.setText("REMOVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btn_wantUpdate.setText("UPDATE");
        btn_wantUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_wantUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_wantUpdate))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_eIdSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_eIdSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btn_wantUpdate))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void option_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option_maleActionPerformed

    private void option_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option_femaleActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if (!isNotNullValue()) {
            showAlert("You need to enter complete employee information!");
        } else if (!isValidateDate()) {
            showAlert("Your date of birth is not format! \n"
                    + "Example: 08-02-2003");
        } else if (!isValidateSalary()) {
            showAlert("Price must be number!");
        } else if (!isValidateGmail()) {
            showAlert("Gmail is not format \n"
                    + "Example: example@gmail.com");
        } else if (!isValidateTelephone()) {
            showAlert("Telephone is not format \n"
                    + "Example: 0123456789");
        } else {
            String eId = txt_eId.getText().trim();
            
            label_id.setForeground(Color.black);
            if (EmployeeList.isDuplicateId(eId)) {
                showAlert("Employee ID is exsited!");
                label_id.setForeground(Color.red);
            } else {
                String eFirstName = txt_eFirstName.getText().trim();
                String eLastName = txt_eLastName.getText().trim();
                String ePhone = txt_ePhone.getText().trim();
                String eEmail = txt_eEmail.getText().trim();
                String eAddress = txt_eAddress.getText().trim();
                Date eDob = Validate.coverToDate(txt_eDob, label_dob);
                float eSalary = Float.parseFloat(txt_eSalary.getText().trim());
                String eAgency = txt_eAgency.getText().trim();
                boolean eGender = option_male.isSelected();

                Employee newEmployee = new Employee(eId, eFirstName, eLastName, ePhone, eEmail, eAddress, eDob, eGender, eSalary, eAgency);
                EmployeeList.addNewEmployee(newEmployee);
                showAlert("Add new employee success!");

                refreshTable();
                clearTxt();
            }
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        int isConfirm = JOptionPane.showConfirmDialog(this, "Are you sure to clear?");
        
        if (isConfirm == 0) clearTxt();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void table_listOfEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_listOfEmployeesMouseClicked
        DefaultTableModel tableModel = (DefaultTableModel) table_listOfEmployees.getModel();
        
        int selectedRow = table_listOfEmployees.getSelectedRow();
        
        String eIdSelected = (String) tableModel.getValueAt(selectedRow, 0);
        txt_eIdSelect.setText(eIdSelected);
    }//GEN-LAST:event_table_listOfEmployeesMouseClicked

    private void btn_wantUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_wantUpdateActionPerformed
        if (txt_eIdSelect.getText().length() == 0) {
            showAlert("Choose some employee please!");
        } else {
            Employee eUpdate = EmployeeList.getEmployeeById(txt_eIdSelect.getText());
            
            if (eUpdate == null) System.out.println("Employee is empty!");
            else {
                SimpleDateFormat sf = new SimpleDateFormat("dd-MM-yyyy");
                
                txt_eId.setText(eUpdate.geteId());
                txt_eFirstName.setText(eUpdate.geteFirstName());
                txt_eLastName.setText(eUpdate.geteLastName());
                txt_ePhone.setText(eUpdate.getePhone());
                txt_eEmail.setText(eUpdate.geteEmail());
                txt_eAddress.setText(eUpdate.geteAddress());
                txt_eDob.setText(sf.format(eUpdate.geteDob()));
                txt_eSalary.setText(String.format("%.1f", eUpdate.getSalary()));
                txt_eAgency.setText(eUpdate.getAgency());
                if (eUpdate.isSex()) option_male.setSelected(true);
                else option_female.setSelected(true);
                
                btn_cancle.setVisible(true);
                btn_update.setVisible(true);
                btn_clear.setVisible(false);
                btn_add.setVisible(false);
                txt_eId.setEditable(false);
            }
        }
    }//GEN-LAST:event_btn_wantUpdateActionPerformed

    private void btn_cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancleActionPerformed
        clearTxt();
        btn_add.setVisible(true);
        btn_update.setVisible(false);
        btn_cancle.setVisible(false);
        btn_clear.setVisible(true);
        txt_eId.setEditable(true);
    }//GEN-LAST:event_btn_cancleActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if (!isNotNullValue()) {
            showAlert("You need to enter complete employee information!");
        } else if (!isValidateDate()) {
            showAlert("Your date of birth is not format! \n"
                    + "Example: 08-02-2003");
        } else if (!isValidateSalary()) {
            showAlert("Price must be number!");
        } else if (!isValidateGmail()) {
            showAlert("Gmail is not format \n"
                    + "Example: example@gmail.com");
        } else if (!isValidateTelephone()) {
            showAlert("Telephone is not format \n"
                    + "Example: 0123456789");
        } else {
            String eId = txt_eId.getText().trim();
            String new_eFirstName = txt_eFirstName.getText().trim();
            String new_eLastName = txt_eLastName.getText().trim();
            String new_ePhone = txt_ePhone.getText().trim();
            String new_eEmail = txt_eEmail.getText().trim();
            String new_eAddress = txt_eAddress.getText().trim();
            Date new_eDob = Validate.coverToDate(txt_eDob, label_dob);
            float new_eSalary = Float.parseFloat(txt_eSalary.getText().trim());
            String new_eAgency = txt_eAgency.getText().trim();
            boolean new_eGender = option_male.isSelected();

            Employee employeeUpdate = EmployeeList.getEmployeeById(eId);
            employeeUpdate.seteFirstName(new_eFirstName);
            employeeUpdate.seteLastName(new_eLastName);
            employeeUpdate.setePhone(new_ePhone);
            employeeUpdate.seteEmail(new_eEmail);
            employeeUpdate.seteAddress(new_eAddress);
            employeeUpdate.seteDob(new_eDob);
            employeeUpdate.setSalary(new_eSalary);
            employeeUpdate.setAgency(new_eAgency);
            employeeUpdate.setSex(new_eGender);
            showAlert("Update employee success!");

            refreshTable();
            clearTxt();
            btn_add.setVisible(true);
            btn_update.setVisible(false);
            btn_cancle.setVisible(false);
            btn_clear.setVisible(true);
            txt_eId.setEditable(true);
            txt_eIdSelect.setText("");
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txt_eIdSelect.getText().length() == 0) {
            showAlert("Choose some employee please!");
        } else {
            int isConfirm = JOptionPane.showConfirmDialog(this, "Are your sure to delete this employee?");
            
            if (isConfirm == 0) {
                EmployeeList.deleteEmployeeById(txt_eIdSelect.getText());
                refreshTable();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void option_sortTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option_sortTypeActionPerformed
        if (option_sortType.getSelectedIndex() == 1) {
            EmployeeList.sortEmployeeSalary();
            refreshTable();
        }
    }//GEN-LAST:event_option_sortTypeActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        String nameSearch = txt_search.getText().trim();
        
        List<Employee> listEmployeeByName = EmployeeList.getListEmployeeByName(nameSearch);
        removeInforTable();
        EmployeeList.addEmployeeToTable(listEmployeeByName, table_listOfEmployees);
    }//GEN-LAST:event_txt_searchKeyReleased

    private void label_idAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_label_idAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_label_idAncestorAdded
    
    public void removeInforTable() {
        DefaultTableModel tableModel = (DefaultTableModel) table_listOfEmployees.getModel();
        
        while (tableModel.getRowCount() > 0) {
            tableModel.removeRow(0);
        }
    }
    
    public void refreshTable() {
        DefaultTableModel tableModel = (DefaultTableModel) table_listOfEmployees.getModel();
        
        while (tableModel.getRowCount() > 0) {
            tableModel.removeRow(0);
        }
        
        EmployeeList.addEmployeeToTable(table_listOfEmployees);
    }
    
    public void test() throws ParseException {
        SimpleDateFormat sf = new SimpleDateFormat("dd-MM-yyyy");
        
        Employee employee1 = new Employee("E01", "John", "Doe", "0912456345", "john.doe@example.com",
                "123 Main St, City", sf.parse("12-2-2003"), true, 21000000f, "Agency A");
        Employee employee2 = new Employee("E02", "Alice", "Smith", "0934324567", "alice.smith@example.com",
                "456 Elm St, Town", sf.parse("24-4-2002"), false, 22200000f, "Agency B");
        Employee employee3 = new Employee("E03", "Bob", "Johnson", "0945645234", "bob.j@example.com",
                "789 Oak St, Village", sf.parse("8-3-2003"), true, 15000000f, "Agency C");
        Employee employee4 = new Employee("E04", "Sarah", "Williams", "0934234523", "sarah.w@example.com",
                "101 Pine St, Suburb", sf.parse("23-5-2002"), false, 8000000f, "Agency A");
        Employee employee5 = new Employee("E05", "Michael", "Brown", "0945234345", "michael.b@example.com",
                "222 Cedar St, County", sf.parse("13-6-2000"), true, 23000000f, "Agency D");
        Employee employee6 = new Employee("E06", "Emily", "Davis", "0978545324", "emily.d@example.com",
                "333 Maple St, Town", sf.parse("21-8-1999"), false, 30000000f, "Agency B");
        Employee employee7 = new Employee("E07", "David", "Wilson", "0945234344", "david.w@example.com",
                "444 Birch St, City", sf.parse("7-5-2003"), true, 22000000f, "Agency C");
        Employee employee8 = new Employee("E08", "Olivia", "Lee", "0954567245", "olivia.l@example.com",
                "555 Redwood St, Suburb", sf.parse("24-11-2002"), false, 12000000f, "Agency A");
        Employee employee9 = new Employee("E09", "James", "Anderson", "0934342237", "james.a@example.com",
                "666 Spruce St, Village", sf.parse("6-10-2001"), true, 6000000f, "Agency D");
        Employee employee10 = new Employee("E10", "Sophia", "Harris", "0953452653", "sophia.h@example.com",
                "777 Willow St, County", sf.parse("22-12-1998"), false, 6000000f, "Agency B");
        
        EmployeeList.addNewEmployee(employee1);
        EmployeeList.addNewEmployee(employee2);
        EmployeeList.addNewEmployee(employee3);
        EmployeeList.addNewEmployee(employee4);
        EmployeeList.addNewEmployee(employee5);
        EmployeeList.addNewEmployee(employee6);
        EmployeeList.addNewEmployee(employee7);
        EmployeeList.addNewEmployee(employee8);
        EmployeeList.addNewEmployee(employee9);
        EmployeeList.addNewEmployee(employee10);
        
        refreshTable();
    }
    
    public void clearTxt() {
        txt_eId.setText("");
        txt_eFirstName.setText("");
        txt_eLastName.setText("");
        txt_ePhone.setText("");
        txt_eEmail.setText("");
        txt_eAddress.setText("");
        txt_eDob.setText("");
        txt_eSalary.setText("");
        txt_eAgency.setText("");
    }
    
    public boolean isNotNullValue() {
        boolean b1 = Validate.isNotEmpty(txt_eId, label_id);
        boolean b2 = Validate.isNotEmpty(txt_eFirstName, label_firstName);
        boolean b3 = Validate.isNotEmpty(txt_eLastName, label_lastName);
        boolean b4 = Validate.isNotEmpty(txt_ePhone, label_phone);
        boolean b5 = Validate.isNotEmpty(txt_eEmail, label_email);
        boolean b6 = Validate.isNotEmpty(txt_eAddress, label_address);
        boolean b7 = Validate.isNotEmpty(txt_eDob, label_dob);
        boolean b8 = Validate.isNotEmpty(txt_eSalary, label_salary);
        boolean b9 = Validate.isNotEmpty(txt_eAgency, label_agency);
        
        boolean b10;
        if (option_male.isSelected() || option_female.isSelected()) {
            b10 = true;
            label_gender.setForeground(Color.black);
        } else {
            b10 = false;
            label_gender.setForeground(Color.red);
        }
        
        return b1 && b2 && b3 && b4 && b5 && b6 && b7 && b8 && b9 && b10;
    }
    
    public boolean isValidateDate() {
        return Validate.isValidateDate(txt_eDob, label_dob);
    }
    
    public boolean isValidateSalary() {
        return Validate.isFormatPrice(txt_eSalary, label_salary);
    }
    
    public boolean isValidateGmail() {
        return Validate.isFormatEmail(txt_eEmail, label_email);
    }
    
    public boolean isValidateTelephone() {
        return Validate.isValidateTelephone(txt_ePhone, label_phone, 10);
    }
    
    public void showAlert(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagmentSystemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagmentSystemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagmentSystemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagmentSystemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeManagmentSystemForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancle;
    private javax.swing.JButton btn_clear;
    private javax.swing.ButtonGroup btn_group_selectGender;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_wantUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_address;
    private javax.swing.JLabel label_agency;
    private javax.swing.JLabel label_dob;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_firstName;
    private javax.swing.JLabel label_gender;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_lastName;
    private javax.swing.JLabel label_phone;
    private javax.swing.JLabel label_salary;
    private javax.swing.JRadioButton option_female;
    private javax.swing.JRadioButton option_male;
    private javax.swing.JComboBox<String> option_sortType;
    private javax.swing.JTable table_listOfEmployees;
    private javax.swing.JTextField txt_eAddress;
    private javax.swing.JTextField txt_eAgency;
    private javax.swing.JTextField txt_eDob;
    private javax.swing.JTextField txt_eEmail;
    private javax.swing.JTextField txt_eFirstName;
    private javax.swing.JTextField txt_eId;
    private javax.swing.JTextField txt_eIdSelect;
    private javax.swing.JTextField txt_eLastName;
    private javax.swing.JTextField txt_ePhone;
    private javax.swing.JTextField txt_eSalary;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
